- hosts: all
  roles:
    - role: apt-packages
      tags: apt-packages
    - role: neovim
      tags: neovim
    - role: docker
      tags: docker
    - role: rbenv
      tags: rbenv
    - role: nodenv
      tags: nodenv
    - role: fish
      tags: fish
