- name: install nodenv
  git :
    repo: https://github.com/nodenv/nodenv.git
    dest: ~/.nodenv
- name: install node-build
  git:
    repo: https://github.com/nodenv/node-build.git
    dest: ~/.nodenv/plugins/node-build
