- name: install neovim repository
  apt_repository : repo=ppa:neovim-ppa/stable
  become: yes

- name: install neovim using apt"
  apt:
    name: 
      - neovim
      - python-pip
      - python3-pip
  become: yes
- name: install neovim pip package
  pip:
    name: neovim
    executable: pip3

